/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as DailyIdRouteImport } from './routes/daily.$id'
import { Route as OfficeIndexRouteImport } from './routes/office.index'
import { Route as OfficeIdRouteImport } from './routes/office.$id'
import { Route as OfficeImportRouteImport } from './routes/office.import'
import { Route as PrintIdRouteImport } from './routes/print.$id'
import { Route as PrintRangeRouteImport } from './routes/print.range'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as ApiOfficeSummaryRouteImport } from './routes/api.office.summary'
import { Route as ApiOfficeSignedIdRouteImport } from './routes/api.office.signed.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyIdRoute = DailyIdRouteImport.update({
  id: '/daily/$id',
  path: '/daily/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeIdRoute = OfficeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeImportRoute = OfficeImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => OfficeRoute,
} as any)
const PrintIdRoute = PrintIdRouteImport.update({
  id: '/print/$id',
  path: '/print/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRangeRoute = PrintRangeRouteImport.update({
  id: '/print/range',
  path: '/print/range',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOfficeSummaryRoute = ApiOfficeSummaryRouteImport.update({
  id: '/api/office/summary',
  path: '/api/office/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOfficeSignedIdRoute = ApiOfficeSignedIdRouteImport.update({
  id: '/api/office/signed/$id',
  path: '/api/office/signed/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/office': typeof OfficeRouteWithChildren
  '/daily/$id': typeof DailyIdRoute
  '/office/$id': typeof OfficeIdRoute
  '/office/import': typeof OfficeImportRoute
  '/print/$id': typeof PrintIdRoute
  '/print/range': typeof PrintRangeRoute
  '/sign/$token': typeof SignTokenRoute
  '/office/': typeof OfficeIndexRoute
  '/api/office/summary': typeof ApiOfficeSummaryRoute
  '/api/office/signed/$id': typeof ApiOfficeSignedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily/$id': typeof DailyIdRoute
  '/office/$id': typeof OfficeIdRoute
  '/office/import': typeof OfficeImportRoute
  '/print/$id': typeof PrintIdRoute
  '/print/range': typeof PrintRangeRoute
  '/sign/$token': typeof SignTokenRoute
  '/office': typeof OfficeIndexRoute
  '/api/office/summary': typeof ApiOfficeSummaryRoute
  '/api/office/signed/$id': typeof ApiOfficeSignedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/office': typeof OfficeRouteWithChildren
  '/daily/$id': typeof DailyIdRoute
  '/office/$id': typeof OfficeIdRoute
  '/office/import': typeof OfficeImportRoute
  '/print/$id': typeof PrintIdRoute
  '/print/range': typeof PrintRangeRoute
  '/sign/$token': typeof SignTokenRoute
  '/office/': typeof OfficeIndexRoute
  '/api/office/summary': typeof ApiOfficeSummaryRoute
  '/api/office/signed/$id': typeof ApiOfficeSignedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/office'
    | '/daily/$id'
    | '/office/$id'
    | '/office/import'
    | '/print/$id'
    | '/print/range'
    | '/sign/$token'
    | '/office/'
    | '/api/office/summary'
    | '/api/office/signed/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daily/$id'
    | '/office/$id'
    | '/office/import'
    | '/print/$id'
    | '/print/range'
    | '/sign/$token'
    | '/office'
    | '/api/office/summary'
    | '/api/office/signed/$id'
  id:
    | '__root__'
    | '/'
    | '/office'
    | '/daily/$id'
    | '/office/$id'
    | '/office/import'
    | '/print/$id'
    | '/print/range'
    | '/sign/$token'
    | '/office/'
    | '/api/office/summary'
    | '/api/office/signed/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfficeRoute: typeof OfficeRouteWithChildren
  DailyIdRoute: typeof DailyIdRoute
  PrintIdRoute: typeof PrintIdRoute
  PrintRangeRoute: typeof PrintRangeRoute
  SignTokenRoute: typeof SignTokenRoute
  ApiOfficeSummaryRoute: typeof ApiOfficeSummaryRoute
  ApiOfficeSignedIdRoute: typeof ApiOfficeSignedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/$id': {
      id: '/daily/$id'
      path: '/daily/$id'
      fullPath: '/daily/$id'
      preLoaderRoute: typeof DailyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/': {
      id: '/office/'
      path: '/'
      fullPath: '/office/'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/$id': {
      id: '/office/$id'
      path: '/$id'
      fullPath: '/office/$id'
      preLoaderRoute: typeof OfficeIdRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/import': {
      id: '/office/import'
      path: '/import'
      fullPath: '/office/import'
      preLoaderRoute: typeof OfficeImportRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/print/$id': {
      id: '/print/$id'
      path: '/print/$id'
      fullPath: '/print/$id'
      preLoaderRoute: typeof PrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/range': {
      id: '/print/range'
      path: '/print/range'
      fullPath: '/print/range'
      preLoaderRoute: typeof PrintRangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/office/summary': {
      id: '/api/office/summary'
      path: '/api/office/summary'
      fullPath: '/api/office/summary'
      preLoaderRoute: typeof ApiOfficeSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/office/signed/$id': {
      id: '/api/office/signed/$id'
      path: '/api/office/signed/$id'
      fullPath: '/api/office/signed/$id'
      preLoaderRoute: typeof ApiOfficeSignedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OfficeRouteChildren {
  OfficeIdRoute: typeof OfficeIdRoute
  OfficeImportRoute: typeof OfficeImportRoute
  OfficeIndexRoute: typeof OfficeIndexRoute
}

const OfficeRouteChildren: OfficeRouteChildren = {
  OfficeIdRoute: OfficeIdRoute,
  OfficeImportRoute: OfficeImportRoute,
  OfficeIndexRoute: OfficeIndexRoute,
}

const OfficeRouteWithChildren =
  OfficeRoute._addFileChildren(OfficeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfficeRoute: OfficeRouteWithChildren,
  DailyIdRoute: DailyIdRoute,
  PrintIdRoute: PrintIdRoute,
  PrintRangeRoute: PrintRangeRoute,
  SignTokenRoute: SignTokenRoute,
  ApiOfficeSummaryRoute: ApiOfficeSummaryRoute,
  ApiOfficeSignedIdRoute: ApiOfficeSignedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
