/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as DailyIdRouteImport } from './routes/daily.$id'
import { Route as OfficeIndexRouteImport } from './routes/office.index'
import { Route as OfficeIdRouteImport } from './routes/office.$id'
import { Route as PrintIdRouteImport } from './routes/print.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyIdRoute = DailyIdRouteImport.update({
  id: '/daily/$id',
  path: '/daily/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeIdRoute = OfficeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OfficeRoute,
} as any)
const PrintIdRoute = PrintIdRouteImport.update({
  id: '/print/$id',
  path: '/print/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/office': typeof OfficeRouteWithChildren
  '/daily/$id': typeof DailyIdRoute
  '/office/$id': typeof OfficeIdRoute
  '/print/$id': typeof PrintIdRoute
  '/office/': typeof OfficeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daily/$id': typeof DailyIdRoute
  '/office/$id': typeof OfficeIdRoute
  '/print/$id': typeof PrintIdRoute
  '/office': typeof OfficeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/office': typeof OfficeRouteWithChildren
  '/daily/$id': typeof DailyIdRoute
  '/office/$id': typeof OfficeIdRoute
  '/print/$id': typeof PrintIdRoute
  '/office/': typeof OfficeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/office' | '/daily/$id' | '/office/$id' | '/print/$id' | '/office/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/daily/$id' | '/office/$id' | '/print/$id' | '/office'
  id:
    | '__root__'
    | '/'
    | '/office'
    | '/daily/$id'
    | '/office/$id'
    | '/print/$id'
    | '/office/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfficeRoute: typeof OfficeRouteWithChildren
  DailyIdRoute: typeof DailyIdRoute
  PrintIdRoute: typeof PrintIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/$id': {
      id: '/daily/$id'
      path: '/daily/$id'
      fullPath: '/daily/$id'
      preLoaderRoute: typeof DailyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/': {
      id: '/office/'
      path: '/'
      fullPath: '/office/'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/$id': {
      id: '/office/$id'
      path: '/$id'
      fullPath: '/office/$id'
      preLoaderRoute: typeof OfficeIdRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/print/$id': {
      id: '/print/$id'
      path: '/print/$id'
      fullPath: '/print/$id'
      preLoaderRoute: typeof PrintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OfficeRouteChildren {
  OfficeIdRoute: typeof OfficeIdRoute
  OfficeIndexRoute: typeof OfficeIndexRoute
}

const OfficeRouteChildren: OfficeRouteChildren = {
  OfficeIdRoute: OfficeIdRoute,
  OfficeIndexRoute: OfficeIndexRoute,
}

const OfficeRouteWithChildren =
  OfficeRoute._addFileChildren(OfficeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfficeRoute: OfficeRouteWithChildren,
  DailyIdRoute: DailyIdRoute,
  PrintIdRoute: PrintIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
